---
name: Checks

on: [push]

jobs:
  test-lint:
    name: 테스트, 문법 확인(Lint)
    runs-on: ubuntu-20.04
    steps:
      - name: Docker Hub 로그인 확인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 코드 작동 여부 Checkout
        uses: actions/checkout@v2
      - name: 테스트
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"